version: "3"
services:
  develop:
    build: .
    ports:
      - "35749:35729"
    environment:
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5000
      MICROSERVICE_TOKEN: null
      GCLOUD_STORAGE: ${GCLOUD_STORAGE}
      GOOGLE_APPLICATION_CREDENTIALS: /opt/query/storage.json
      BUCKET_FREEZE: query-freeze
      FASTLY_ENABLED: "false"

    command: develop
    volumes:
      - ./app:/opt/query/app
