version: "3"
services:
  test:
    build: .
    ports:
      - "5000:5000"
    container_name: query-test
    environment:
      NODE_ENV: test
      PORT: 5000
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://query.default.svc.cluster.local:5000
      API_VERSION: v1
      CT_TOKEN: cttoken
      CT_REGISTER_MODE: auto
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
    command: test
