version: "3"
services:
  develop:
    build: .
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      NODE_PATH: app/src
      CT_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:5001
      API_VERSION: v1
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      CT_REGISTER_MODE: auto
      GCLOUD_STORAGE: ${GCLOUD_STORAGE}
      GOOGLE_APPLICATION_CREDENTIALS: /opt/query/storage.json
      BUCKET_FREEZE: query-freeze
      FASTLY_ENABLED: "false"

    command: develop
    volumes:
      - ./app:/opt/query/app
