version: "3"
services:
  test:
    build: .
    ports:
      - "5000:5000"
    container_name: query-test
    environment:
      NODE_ENV: test
      PORT: 5000
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://query.default.svc.cluster.local:5000
      MICROSERVICE_TOKEN: cttoken
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
